# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20170712_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='idFacebook',
            field=models.BigIntegerField(unique=True),
        ),
    ]
