# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0001_initial'),
        ('noticia', '0002_auto_20170715_1509'),
        ('usuario', '0004_auto_20170712_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='noticias',
            field=models.ManyToManyField(to='noticia.Noticia'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sitios',
            field=models.ManyToManyField(to='sitio.Sitio'),
        ),
    ]
