# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20170715_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='idFacebook',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
