# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_auto_20170725_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.URLField(),
        ),
    ]
