# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_auto_20170725_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
