# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_usuario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
    ]
