# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_auto_20170810_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='noticias',
            field=models.ManyToManyField(blank=True, null=True, to='noticia.Noticia'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sitios',
            field=models.ManyToManyField(blank=True, null=True, to='sitio.Sitio'),
        ),
    ]
