# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 00:56
from __future__ import unicode_literals

import apps.categoria_mapa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria_mapa', '0002_categoriamapa_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriamapa',
            name='imagen',
            field=models.ImageField(upload_to=apps.categoria_mapa.models.upload_location),
        ),
    ]
