# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcategoria_mapa', '0001_initial'),
        ('categoria_mapa', '0003_auto_20170728_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriamapa',
            name='subcategoria_mapa',
            field=models.ManyToManyField(to='subcategoria_mapa.SubcategoriaMapa'),
        ),
    ]
