# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria_mapa', '0004_categoriamapa_subcategoria_mapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriamapa',
            name='subcategoria_mapa',
            field=models.ManyToManyField(related_name='subcategoria', to='subcategoria_mapa.SubcategoriaMapa'),
        ),
    ]
