# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria_mapa', '0005_auto_20170816_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriamapa',
            name='subcategoria_mapa',
            field=models.ManyToManyField(to='subcategoria_mapa.SubcategoriaMapa'),
        ),
    ]
