# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 01:28
from __future__ import unicode_literals

import apps.categoria_mapa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria_mapa', '0009_categoriamapa_icono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriamapa',
            name='icono',
            field=models.ImageField(upload_to=apps.categoria_mapa.models.upload_location_3),
        ),
    ]
