# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 23:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imagen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tag', '0001_initial'),
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('titular', models.CharField(max_length=30)),
                ('lead', models.CharField(max_length=30)),
                ('texto', models.TextField()),
                ('video', models.URLField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ManyToManyField(to='categoria.Categoria')),
                ('imagenes', models.ManyToManyField(to='imagen.Imagen')),
                ('tag', models.ManyToManyField(to='tag.Tag')),
            ],
        ),
    ]
