# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0002_auto_20170715_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='video',
            field=models.URLField(blank=True),
        ),
    ]
