# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0003_auto_20170721_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='destacada',
            field=models.BooleanField(default=False),
        ),
    ]
