# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0004_noticia_destacada'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='duracion',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titular',
            field=models.CharField(max_length=100),
        ),
    ]
