# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0005_auto_20170722_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='duracion',
            field=models.CharField(max_length=150),
        ),
    ]
