# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0007_auto_20170722_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagen_video',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
