# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0008_noticia_imagen_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='titular',
            field=models.CharField(max_length=150),
        ),
    ]
