# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0009_auto_20170724_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
