# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0010_noticia_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='video',
            field=models.TextField(blank=True),
        ),
    ]
