# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0012_auto_20170814_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='imagenes',
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagenes',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
