# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagen', '0002_auto_20170725_1436'),
        ('noticia', '0013_auto_20170815_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='imagenes',
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagenes',
            field=models.ManyToManyField(to='imagen.Imagen'),
        ),
    ]
