# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0014_auto_20170815_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
