# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0016_auto_20171014_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='web',
            field=models.BooleanField(default=False),
        ),
    ]
