# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0017_auto_20171103_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
