# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0018_noticia_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
