# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0018_auto_20171125_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='slug',
            field=models.SlugField(default='', max_length=200),
        ),
    ]
