# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-25 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0025_auto_20171125_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
    ]
