# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 14:36
from __future__ import unicode_literals

import apps.imagen.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(upload_to=apps.imagen.models.upload_location),
        ),
    ]
