# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagen', '0002_auto_20170725_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
