# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 15:01
from __future__ import unicode_literals

import apps.imagen.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagen', '0003_auto_20170815_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=apps.imagen.models.upload_location),
        ),
    ]
