# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagen', '0006_auto_20170819_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='nombre',
            field=models.CharField(blank=True, default='Imagen', max_length=150, null=True),
        ),
    ]
