# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 16:01
from __future__ import unicode_literals

import apps.imagen.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagen', '0014_auto_20170926_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(blank=True, default='imagen_f', upload_to=apps.imagen.models.upload_location),
        ),
    ]
