# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='mensaje',
            field=models.TextField(max_length=140),
        ),
    ]
