# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadistica', '0002_auto_20170729_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='compartirnoticia',
            name='dispositivo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardarnoticia',
            name='dispositivo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingreso',
            name='dispositivo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='llamarsitio',
            name='dispositivo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitarsitio',
            name='dispositivo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visualizarnoticia',
            name='dispositivo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
