# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadistica', '0003_auto_20170731_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compartirnoticia',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='compartirnoticia',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='guardarnoticia',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='guardarnoticia',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='llamarsitio',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='llamarsitio',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='visitarsitio',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='visitarsitio',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='visualizarnoticia',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='visualizarnoticia',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
