# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0007_auto_20170731_1114'),
        ('usuario', '0010_auto_20170731_1622'),
        ('estadistica', '0004_auto_20170731_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookSitio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('dispositivo', models.IntegerField()),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio.Sitio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='InstagramSitio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('dispositivo', models.IntegerField()),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio.Sitio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario')),
            ],
        ),
    ]
