# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_auto_20170824_1459'),
        ('estadistica', '0005_facebooksitio_instagramsitio'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('dispositivo', models.IntegerField()),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario')),
            ],
        ),
    ]
