# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estadistica', '0006_ingresologin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresologin',
            name='usuario',
        ),
    ]
