# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('estadistica',
         '0008_savenews_sharefacebook_sharegoogle_shareinstagram_sharetwitter_visitindex_visitnews_visitplace'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShareInstagram',
            new_name='VisitMap',
        ),
    ]
