# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0017_auto_20171103_1115'),
        ('sitio', '0026_auto_20170920_1804'),
        ('estadistica', '0009_auto_20171014_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharefacebook',
            name='noticia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='noticia.Noticia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharegoogle',
            name='noticia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='noticia.Noticia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharetwitter',
            name='noticia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='noticia.Noticia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitnews',
            name='noticia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='noticia.Noticia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitplace',
            name='sitio',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='sitio.Sitio'),
        ),
    ]
