# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='nombre',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
