# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_auto_20170722_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
