# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0003_auto_20170722_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
