# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='color',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
