# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_categoria_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='azul',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria',
            name='rojo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria',
            name='verde',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
