# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0005_categoria_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='visibleApp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='visibleWeb',
            field=models.BooleanField(default=True),
        ),
    ]
