# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitio',
            name='categoria',
            field=models.ManyToManyField(related_name='categoria_sitio', to='categoria_mapa.CategoriaMapa'),
        ),
    ]
