# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0002_auto_20170721_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitio',
            name='direccion',
            field=models.CharField(max_length=50),
        ),
    ]
