# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0003_auto_20170726_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitio',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='instagram',
            field=models.URLField(blank=True),
        ),
    ]
