# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0004_auto_20170726_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitio',
            name='titulo',
            field=models.CharField(max_length=150),
        ),
    ]
