# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcategoria_mapa', '0001_initial'),
        ('sitio', '0007_auto_20170731_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitio',
            name='categoria',
        ),
        migrations.AddField(
            model_name='sitio',
            name='subcategoria',
            field=models.ManyToManyField(related_name='categoria_sitio', to='subcategoria_mapa.SubcategoriaMapa'),
        ),
    ]
