# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0008_auto_20170816_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitio',
            name='subcategoria',
            field=models.ManyToManyField(related_name='subcategoria_sitio', to='subcategoria_mapa.SubcategoriaMapa'),
        ),
    ]
