# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcategoria_mapa', '0001_initial'),
        ('sitio', '0010_remove_sitio_subcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitio',
            name='subcategoria',
            field=models.ManyToManyField(related_name='subcategoria_sitio', to='subcategoria_mapa.SubcategoriaMapa'),
        ),
    ]
