# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagen', '0004_auto_20170815_1001'),
        ('subcategoria_mapa', '0001_initial'),
        ('sitio', '0013_remove_sitio_imagenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitio',
            name='imagenes',
            field=models.ManyToManyField(to='imagen.Imagen'),
        ),
        migrations.AddField(
            model_name='sitio',
            name='subcategoria',
            field=models.ManyToManyField(related_name='subcategoria_sitio', to='subcategoria_mapa.SubcategoriaMapa'),
        ),
    ]
