# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0014_auto_20170816_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitio',
            name='imagenes',
            field=models.ManyToManyField(related_name='imagen_sitio', to='imagen.Imagen'),
        ),
    ]
