# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagen', '0004_auto_20170815_1001'),
        ('sitio', '0016_remove_sitio_imagenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitio',
            name='imagenes',
            field=models.ManyToManyField(related_name='imagen_sitio', to='imagen.Imagen'),
        ),
    ]
