# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0017_sitio_imagenes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitio',
            name='imagenes',
            field=models.ManyToManyField(to='imagen.Imagen'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='subcategoria',
            field=models.ManyToManyField(related_name='sitio', to='subcategoria_mapa.SubcategoriaMapa'),
        ),
    ]
