# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 23:04
from __future__ import unicode_literals

import apps.sitio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0025_auto_20170920_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitio',
            name='logo',
            field=models.ImageField(default=1, upload_to=apps.sitio.models.upload_location),
            preserve_default=False,
        ),
    ]
