# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Votaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispositivo_id', models.TextField(unique=True)),
                ('so', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Youtuber',
            fields=[
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='votaciones',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activacion_youtuber.Youtuber'),
        ),
    ]
