# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activacion_youtuber', '0002_auto_20170926_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='votaciones',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='votaciones',
            name='hora',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
