# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_auto_20170824_1459'),
        ('activacion_youtuber', '0003_auto_20170926_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='votaciones',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario'),
            preserve_default=False,
        ),
    ]
