# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activacion_youtuber', '0004_votaciones_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtuber',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
